{% set name = "ntbtls" %}
{% set version = "0.3.1" %}
{% set sha256 = "8922181fef523b77b71625e562e4d69532278eabbd18bc74579dbe14135729ba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.gnupg.org/ftp/gcrypt/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - ./configure --prefix=$PREFIX
    - make
    - make install
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('ntbtls') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libgpg-error
    - libksba
    - libgcrypt
    - zlib
  run:
    - zlib

test:
  commands:

about:
  home: https://www.gnupg.org/software/ntbtls/index.html
  summary: Not Too Bad TLS
  license: LGPL-3
  license_family: GPL
  license_file: COPYING
  description: |
    ntbTLS is a tiny TLS 1.2 only implementation designed to be used with Libgcrypt
    and LibKSBA. In particular, this library has no certificate verification code
    - this need to be done by the caller. For example the GnuPG component dirmngr
    already has code to verify certificates (for CRL and OCSP checking) and thus
    ntbTLS is a good fit for accessing objects over the network.
extra:
  recipe-maintainers:
    - mariusvniekerk
